// import './HomePage.story'
// import './VocaPlayPage.story'
// import './component/DetailDictPage.story'
// import '../../component/IndexSectionList.story'
// import './GroupVocaPage.story'
import './component/VocaCard.story'