
export const DAY_MS = 86400000
export const BASE_URL = 'https://jzyy-1259360612.cos.ap-chengdu.myqcloud.com/'

// 主目录
export const FILE_ROOT_DIR = '/'
export const VOCABULARY_DIR = 'vocabulary/'
export const READING_DIR = 'reading/'
export const USER_DIR = 'user/'
export const SHARE_DIR = 'share/'



// 同步指令(任务数据)
export const COMMAND_CREATE_TASK = "COMMAND_CREATE_TASK"
export const COMMAND_DELETE_TASK = "COMMAND_DELETE_TASK"
export const COMMAND_MODIFY_TASK = "COMMAND_MODIFY_TASK"
export const COMMAND_MODIFY_PASSED = "COMMAND_MODIFY_PASSED"
export const COMMAND_MODIFY_SCORE = "COMMAND_MODIFY_SCORE"
export const COMMAND_MODIFY_LISTEN_TIMES = "COMMAND_MODIFY_LISTEN_TIMES"
export const COMMAND_BATCH_MODIFY_TASK_DATE = "COMMAND_BATCH_MODIFY_TASK_DATE"

// 同步指令(生词数据)
export const COMMAND_GROUP_CREATE = "COMMAND_GROUP_CREATE"
export const COMMAND_GROUP_SET_DEFAULT = "COMMAND_GROUP_SET_DEFAULT"
export const COMMAND_GROUP_DELETE = "COMMAND_GROUP_DELETE"
export const COMMAND_GROUP_ADD_WORDS = "COMMAND_GROUP_ADD_WORDS"
export const COMMAND_GROUP_REMOVE_WORDS = "COMMAND_GROUP_REMOVE_WORDS"
export const COMMAND_GROUP_MODIFY_NAME = "COMMAND_GROUP_MODIFY_NAME"
export const COMMAND_GROUP_MODIFY_LISTEN_TIMES = "COMMAND_GROUP_MODIFY_LISTEN_TIMES"
export const COMMAND_GROUP_MODIFY_TEST_TIMES = "COMMAND_GROUP_MODIFY_TEST_TIMES"
export const COMMAND_GROUP_SORT = "COMMAND_GROUP_SORT"
